### ISSUE TITLE
Boilerplate is outdated

### ISSUE THREAD

**Issue by sjorobekov** [adonisjs-community/ally-starter-kit#2]
Seems like boilerplate isn't compatible with adonis v6 and/or ally v5.

**Comment by afgallo** [comment]
Hi @sjorobekov luckily I came across your comment before I started delving into building a custom ally connector for Auth0.

@thetutlage would you recommend to use this template still? From a quick glance, it doesn't look too different to one of the current Ally providers such as https://github.com/adonisjs/ally/blob/develop/src/drivers/github.ts

Excited to use Adonis! Thanks so much for your work @thetutlage.

**Comment by thetutlage** [comment]
It should be all good now. Please download the `main` branch of the repo and give it a try. https://github.com/adonisjs-community/ally-starter-kit
